{
  "action": {
    "error": {
      "variety": [
        "Omission"
      ],
      "vector": [
        "Carelessness"
      ]
    }
  },
  "actor": {
    "internal": {
      "motive": [
        "NA"
      ],
      "variety": [
        "System admin"
      ]
    }
  },
  "asset": {
    "assets": [
      {
        "amount": 2,
        "variety": "S - Database"
      }
    ],
    "cloud": [
      "Unknown"
    ]
  },
  "attribute": {
    "confidentiality": {
      "data": [
        {
          "variety": "Personal"
        }
      ],
      "data_disclosure": "Yes",
      "data_total": 113000000,
      "data_victim": [
        "Customer"
      ],
      "state": [
        "Stored unencrypted"
      ]
    }
  },
  "confidence": "Low",
  "discovery_method": {
    "external": {
      "variety": [
        "Security researcher"
      ]
    }
  },
  "incident_id": "14096790-352a-11e9-8dbb-275658e06f31",
  "plus": {
    "analysis_status": "Reviewed",
    "analyst": "Hylender",
    "created": "2019-02-20T22:22:06.679Z",
    "dbir_year": 2019,
    "event_chain": [
      {
        "action": "err",
        "actor": "int",
        "asset": "srv",
        "attribute": "cp"
      }
    ],
    "github": "12321",
    "master_id": "08fbe587-5ddd-4151-8ced-68bee8cb8326",
    "modified": "2019-02-20T22:22:06.679Z",
    "sub_source": "priority",
    "timeline": {
      "notification": {
        "year": 2018
      }
    }
  },
  "reference": "https://www.pymnts.com/news/security-and-risk/2018/mindbody-fitness-customer-data-breach/",
  "schema_version": "1.3.6",
  "security_incident": "Confirmed",
  "source_id": "vcdb",
  "summary": "two servers owned by fitness company mindbody left 113 million users with PII exposed to internet.",
  "targeted": "NA",
  "timeline": {
    "incident": {
      "year": 2018
    }
  },
  "victim": {
    "country": [
      "US"
    ],
    "employee_count": "Unknown",
    "government": [
      "NA"
    ],
    "industry": "541",
    "region": [
      "019021"
    ],
    "victim_id": "mindbody"
  }
}