{
  "action": {
    "malware": {
      "variety": [
        "Ransomware"
      ],
      "vector": [
        "Unknown"
      ]
    }
  },
  "actor": {
    "external": {
      "country": [
        "Unknown"
      ],
      "motive": [
        "Financial"
      ],
      "region": [
        "000000"
      ],
      "variety": [
        "Organized crime"
      ]
    }
  },
  "asset": {
    "assets": [
      {
        "variety": "S - Unknown"
      }
    ],
    "cloud": [
      "Unknown"
    ],
    "role": [
      "IT"
    ]
  },
  "attribute": {
    "availability": {
      "variety": [
        "Obscuration"
      ]
    },
    "confidentiality": {
      "data": [
        {
          "variety": "Medical"
        }
      ],
      "data_disclosure": "Potentially",
      "data_victim": [
        "Patient"
      ],
      "state": [
        "Stored"
      ]
    },
    "integrity": {
      "variety": [
        "Software installation"
      ]
    }
  },
  "confidence": "High",
  "discovery_method": {
    "external": {
      "variety": [
        "Actor disclosure"
      ]
    }
  },
  "incident_id": "8f273660-146b-11eb-ac54-3bea5c26f172",
  "plus": {
    "analysis_status": "Reviewed",
    "analyst": "planglois",
    "attribute": {
      "confidentiality": {
        "data_abuse": "Unknown"
      }
    },
    "created": "2020-10-22T18:34:52.867Z",
    "dbir_year": 2021,
    "event_chain": [
      {
        "action": "unk",
        "actor": "ext",
        "asset": "srv",
        "attribute": "cp",
        "summary": "somehow gained access to the environment"
      },
      {
        "action": "mal",
        "actor": "ext",
        "asset": "srv",
        "attribute": "ia",
        "summary": "malware installed"
      },
      {
        "action": "mal",
        "actor": "ext",
        "asset": "srv",
        "attribute": "cp",
        "summary": "potentially stole stuff"
      },
      {
        "action": "mal",
        "actor": "ext",
        "asset": "srv",
        "attribute": "au",
        "summary": "Encrypted stuff"
      }
    ],
    "github": "14766",
    "master_id": "fee0cbd4-6241-4ff2-9b50-826f47c178d0",
    "modified": "2020-10-22T18:34:52.867Z",
    "sub_source": "phidbr",
    "timeline": {
      "notification": {
        "day": 27,
        "month": 12,
        "year": 2019
      }
    }
  },
  "reference": "https://www.databreaches.net/tx-san-antonio-mental-health-and-substance-abuse-services-provider-hit-by-ransomware-attack/",
  "schema_version": "1.3.6",
  "security_incident": "Confirmed",
  "source_id": "vcdb",
  "summary": "Center for Health Care Services, in San Antonio Texas, experienced a ransomware attack",
  "targeted": "Opportunistic",
  "timeline": {
    "incident": {
      "month": 12,
      "year": 2019
    }
  },
  "value_chain": {
    "cash-out": {
      "notes": "VERIS 1.3.6: value_chain.development.variety.Cryptocurrency added because action.malware.variety.Ransomware exists.",
      "variety": [
        "Cryptocurrency"
      ]
    }
  },
  "victim": {
    "country": [
      "US"
    ],
    "employee_count": "10001 to 25000",
    "government": [
      "NA"
    ],
    "industry": "62133",
    "locations_affected": 1,
    "region": [
      "019021"
    ],
    "state": "TX",
    "victim_id": "Center for Health Care Services"
  }
}